### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wsargent**
Show how to get a prebuilt fastdebug from chriswhocodes

### CODE REVIEW

**Comment by cl4es** [comment]
Thanks for opening this pull request - I agree some pointers to existing fastdebug binaries is a good addition.

Does jabba work with tar.xz archives? If so we could add links to builds.shipilev.net:

jdk/jdk: https://builds.shipilev.net/openjdk-jdk/openjdk-jdk-latest-linux-x86_64-fastdebug.tar.xz
JDK 15: https://builds.shipilev.net/openjdk-jdk15/openjdk-jdk15-latest-linux-x86_64-fastdebug.tar.xz
JDK 14: https://builds.shipilev.net/openjdk-jdk14/openjdk-jdk14-latest-linux-x86_64-fastdebug.tar.xz
...

**Review by cl4es — APPROVED** [review]

**Comment by wsargent** [comment]
Jabba does support xz: 

```
jabba install 1.8.0-custom=tgx+http://example.com/distribution.tar.xz
```

**Comment by wsargent** [comment]
Looks like https://github.com/ojdkbuild/ojdkbuild doesn't host fastdebug builds, so it's good as is...

**Comment by wsargent** [comment]
Added links to builds.shipilev.net.

**Review by cl4es — APPROVED** [review]

**Pull request merged**
